"""Herdr wait-loop + handoff writeout (plan → wait → compact → next).

Thin prototype: dry-run prints the plan; live mode uses Herdr agent wait/read
when available, then writes a session handoff from a template.

Does not SSH-hammer, NFS-filewalk, or reload burn transcripts.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from datetime import date
from pathlib import Path
from typing import Any, Optional

from tok_tua.scale import spawn_herdr_agent

_REPO = Path(__file__).resolve().parents[1]
_SAFE_NAME = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,48}$")

HANDOFF_TEMPLATE = """# Session handoff — {title}

**Date:** {date}
**Agent name:** `{name}`
**CLI / model:** `{cli}` / `{model}`
**Scale:** herdr wait-loop
**Until:** `{until}`

---

## 0. Paste into next chat (first message)

```text
Continue from {handoff_path}
Routing: prompt → context citations (if available) → Headroom → LiteLLM
Prefer local gateway models; sensitive care data stays local-only.
```

---

## 1. Done

- (fill after agent completes)

## 2. Open / next

- (fill next steps)

## 3. Session evidence (IDs only)

| Surface | ID / path |
|---------|-----------|
| Herdr agent | `{name}` |
| Wait status | `{status}` |
| Handoff file | `{handoff_path}` |

## 4. Compact agent output (bounded)

```
{compact}
```

---

*Generated by `python -m tok_tua loop`. Do not paste bulk session dumps.*
"""


def _run_herdr(args: list[str], *, timeout: float = 30.0) -> dict[str, Any]:
    try:
        proc = subprocess.run(
            ["herdr", *args],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except FileNotFoundError:
        return {"ok": False, "error": "herdr not on PATH"}
    except (OSError, subprocess.TimeoutExpired) as exc:
        return {"ok": False, "error": str(exc)}
    out = (proc.stdout or "").strip()
    err = (proc.stderr or "").strip()
    parsed: Any = None
    if out:
        try:
            parsed = json.loads(out)
        except json.JSONDecodeError:
            parsed = None
    return {
        "ok": proc.returncode == 0,
        "returncode": proc.returncode,
        "stdout": out[:4000],
        "stderr": err[:1000],
        "json": parsed,
    }


def herdr_wait(target: str, *, until: str = "done", timeout_ms: int = 600_000) -> dict[str, Any]:
    if not _SAFE_NAME.match(target):
        return {"ok": False, "error": f"invalid agent name {target!r}"}
    until_n = (until or "done").strip().lower()
    if until_n not in {"idle", "working", "blocked", "done", "unknown"}:
        return {"ok": False, "error": f"invalid until state {until!r}"}
    wall = max(5.0, min(timeout_ms / 1000.0 + 5.0, 3600.0))
    return _run_herdr(
        ["agent", "wait", target, "--until", until_n, "--timeout", str(timeout_ms)],
        timeout=wall,
    )


def herdr_read(target: str, *, max_chars: int = 4000) -> dict[str, Any]:
    if not _SAFE_NAME.match(target):
        return {"ok": False, "error": f"invalid agent name {target!r}"}
    result = _run_herdr(["agent", "read", target], timeout=15.0)
    text = result.get("stdout") or ""
    if len(text) > max_chars:
        text = text[: max_chars // 2] + "\n…\n" + text[-max_chars // 2 :]
    result["compact"] = text
    return result


def write_handoff(
    *,
    name: str,
    cli: str,
    model: str,
    until: str,
    status: str,
    compact: str,
    out_dir: Path | None = None,
) -> Path:
    root = out_dir or (_REPO / "docs" / "handoffs")
    root.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    path = root / f"SESSION_HANDOFF_{today}_{name}.md"
    rel = str(path.relative_to(_REPO)) if path.is_relative_to(_REPO) else str(path)
    body = HANDOFF_TEMPLATE.format(
        title=name,
        date=today,
        name=name,
        cli=cli or "?",
        model=model or "?",
        until=until,
        status=status,
        handoff_path=rel,
        compact=(compact or "(empty)").strip()[:4000],
    )
    path.write_text(body, encoding="utf-8")
    return path


def run_loop(
    *,
    cli: str | None = None,
    model: str | None = None,
    name: str = "tok-loop",
    cwd: str | None = None,
    until: str = "done",
    timeout_ms: int = 600_000,
    dry_run: bool = True,
    spawn: bool = True,
    write: bool = True,
    out_dir: Path | None = None,
) -> dict[str, Any]:
    """Spawn (optional) → wait → read → handoff writeout."""
    if not _SAFE_NAME.match(name):
        return {"ok": False, "error": f"invalid agent name {name!r}"}

    plan_out: dict[str, Any] = {
        "ok": True,
        "dry_run": dry_run,
        "name": name,
        "cli": cli,
        "model": model,
        "until": until,
        "timeout_ms": timeout_ms,
        "steps": [],
    }

    if spawn:
        spawn_result = spawn_herdr_agent(
            name,
            cli=cli,
            model=model,
            cwd=cwd or str(_REPO),
            dry_run=dry_run,
        )
        plan_out["steps"].append({"step": "spawn", **spawn_result})
        if not spawn_result.get("ok"):
            plan_out["ok"] = False
            return plan_out

    if dry_run:
        plan_out["steps"].append(
            {
                "step": "wait",
                "dry_run": True,
                "argv": [
                    "herdr",
                    "agent",
                    "wait",
                    name,
                    "--until",
                    until,
                    "--timeout",
                    str(timeout_ms),
                ],
            }
        )
        plan_out["steps"].append(
            {
                "step": "read",
                "dry_run": True,
                "argv": ["herdr", "agent", "read", name],
            }
        )
        if write:
            path = write_handoff(
                name=name,
                cli=cli or "?",
                model=model or "?",
                until=until,
                status="dry-run",
                compact="(dry-run — no agent output)",
                out_dir=out_dir,
            )
            plan_out["steps"].append({"step": "handoff", "path": str(path), "dry_run": True})
            plan_out["handoff"] = str(path)
        return plan_out

    wait_result = herdr_wait(name, until=until, timeout_ms=timeout_ms)
    plan_out["steps"].append({"step": "wait", **wait_result})
    if not wait_result.get("ok"):
        plan_out["ok"] = False
    read_result = herdr_read(name)
    plan_out["steps"].append(
        {"step": "read", "ok": read_result.get("ok"), "chars": len(read_result.get("compact") or "")}
    )
    status = "ok" if wait_result.get("ok") else (wait_result.get("error") or "wait-failed")
    compact = read_result.get("compact") or wait_result.get("stdout") or ""
    if write:
        path = write_handoff(
            name=name,
            cli=cli or "?",
            model=model or "?",
            until=until,
            status=str(status),
            compact=str(compact),
            out_dir=out_dir,
        )
        plan_out["steps"].append({"step": "handoff", "path": str(path)})
        plan_out["handoff"] = str(path)
    return plan_out


def main(argv: Optional[list[str]] = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(
        description="Herdr wait-loop + handoff writeout (use --dry-run first)",
    )
    parser.add_argument("--cli", default=None)
    parser.add_argument("--model", default=None)
    parser.add_argument("--name", default="tok-loop")
    parser.add_argument("--cwd", default=None)
    parser.add_argument(
        "--until",
        default="done",
        choices=["idle", "working", "blocked", "done", "unknown"],
    )
    parser.add_argument("--timeout-ms", type=int, default=600_000)
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=os.environ.get("TOK_TUA_LOOP_DRY_RUN", "1") != "0",
        help="Print plan / write template handoff without live wait (default on)",
    )
    parser.add_argument(
        "--live",
        action="store_true",
        help="Actually spawn/wait/read (disables default dry-run)",
    )
    parser.add_argument("--no-spawn", action="store_true", help="Wait on existing agent only")
    parser.add_argument("--no-write", action="store_true", help="Skip handoff file write")
    parser.add_argument("--out-dir", default=None, help="Handoff output directory")
    args = parser.parse_args(argv)

    dry_run = not args.live if args.live else args.dry_run
    result = run_loop(
        cli=args.cli,
        model=args.model,
        name=args.name,
        cwd=args.cwd,
        until=args.until,
        timeout_ms=args.timeout_ms,
        dry_run=dry_run,
        spawn=not args.no_spawn,
        write=not args.no_write,
        out_dir=Path(args.out_dir) if args.out_dir else None,
    )
    print(json.dumps(result, indent=2, default=str))
    return 0 if result.get("ok") else 1


if __name__ == "__main__":
    raise SystemExit(main())
